services:
  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.13.0-debian}
    restart: always
    volumes:
      - ./services/apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    environment:
      - ETCD_HOST=${ETCD_HOST:-etcd:2379}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge
